opa_data_path: "/mnt/d"

# "prod" | "dev"
app_env: "prod"

http:
  read_header_timeout: 5
  idle_timeout: 30
  context_time: 3 

db:
  timeout: 3
  read_time_out: 5
  write_time_out: 5
  parse_time: true
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30
  conn_max_idle_time: 5 

logger:
  file_name: "/mnt/d/log/server.log" # "prod" 인 경우 필요
  max_size: 20 # MB
  max_backups: 3
  max_age: 28
  compress: true

security:
  allowed_hosts:
    - "127.0.0.1:4001"
    - "localhost:4001"
  ssl_redirect: false
  ssl_host: ""
  sts_seconds: 86400
  sts_include_subdomains: true
  frame_deny: true
  content_type_no_sniff: true
  # content_security_policy: "default-src 'self'"
  ie_no_open: true
  referrer_policy: "strict-origin-when-cross-origin"
  ssl_proxy_headers:
    # X-Forwarded-Proto: "https"
