// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/services/clients": {
            "get": {
                "description": "Returns a map of all registered OPA clients grouped by service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get all registered OPA clients",
                "responses": {
                    "200": {
                        "description": "Map of service name to client list",
                        "schema": {
                            "$ref": "#/definitions/handler.clientGroupResponse"
                        }
                    }
                }
            }
        },
        "/services/{service}/bundle": {
            "get": {
                "description": "Downloads an OPA bundle file (.tar.gz) for the specified service.\nBy default, the latest **regular** bundle is served.\nTo download a **delta** bundle, use the query ` + "`" + `?type=delta` + "`" + `.\nTo request a specific version of the regular bundle, use the query ` + "`" + `?version=X.Y` + "`" + `.\nSupports ETag validation using the ` + "`" + `If-None-Match` + "`" + ` header.",
                "produces": [
                    "application/gzip"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Download OPA bundle file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name (must be listed in config.clients.service)",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bundle type: 'regular' (default) or 'delta'",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Regular bundle version in format 'X.Y' (e.g., 1.2)",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested bundle file (.tar.gz)",
                        "schema": {
                            "type": "file"
                        },
                        "headers": {
                            "ETag": {
                                "type": "string",
                                "description": "ETag header containing current bundle hash"
                            }
                        }
                    },
                    "304": {
                        "description": "Not Modified - Client already has the latest bundle",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameters or file not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error while serving the bundle",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            }
        },
        "/services/{service}/clients": {
            "get": {
                "description": "Returns a list of registered OPA client addresses for the specified service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get clients by service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name \u003cbr\u003e Only services listed in clients.service of the config file are allowed.",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of registered clients",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid service parameters",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers one or more OPA SDK client addresses for the specified service.\nAccepts a JSON array of client URLs (e.g., IP or domain).\nThese clients will be notified via webhook when a new bundle is available.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Register OPA webhook client addresses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name (must be listed in config.clients.service)",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List of OPA client addresses (IP or domain)",
                        "name": "clients",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Clients registered successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameters, JSON format or no clients provided",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "409": {
                        "description": "Conflict - one or more clients already registered or registration failed",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a specific client (by IP or DNS) or all clients for a service if no client is specified.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Delete one or all OPA clients for a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name \u003cbr\u003e Only services listed in clients.service of the config file are allowed.",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client address (IP or domain). If omitted, all clients will be deleted.",
                        "name": "client",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Client(s) deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameters",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Client not found",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    }
                }
            }
        },
        "/services/{service}/data/trigger": {
            "post": {
                "description": "Triggers OPA bundle regeneration.\n1. Builds ` + "`" + `data.json` + "`" + ` for the given service\n2. Compares with previous version to generate ` + "`" + `patch.json` + "`" + `\n3. If changes are found, creates ` + "`" + `delta.tar.gz` + "`" + ` and ` + "`" + `regular-vX.X.tar.gz` + "`" + ` bundles\n4. Sends webhook POST /hooks/bundle-update?type=delta to notify OPA SDK clients",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Trigger policy DB update and generate OPA bundles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name (only services defined in config.clients.service are allowed)",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - No changes detected in data.json (no new bundles created)",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted - Bundles generated and notification will be sent to OPA clients",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameter",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error during data/bundle generation",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "501": {
                        "description": "Service not yet supported",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            }
        },
        "/services/{service}/policy": {
            "post": {
                "description": "Uploads a ` + "`" + `policy.rego` + "`" + ` file via multipart/form-data and saves it into the service-specific bundle directory.\nOnly services defined in ` + "`" + `clients.service` + "`" + ` of the config file are allowed.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Upload a policy.rego file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name (must be listed in config.clients.service)",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "policy.rego file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created - The policy.rego file was saved successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameter or malformed request",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error while saving the policy file",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            }
        },
        "/services/{service}/policy/trigger": {
            "post": {
                "description": "Triggers regeneration of the regular bundle (policy.rego and related files).\nIf changes are detected, sends a webhook notification to OPA SDK clients via POST /hooks/bundle-update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Trigger policy.rego update and generate regular OPA bundle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name (only services defined in config.clients.service are allowed)",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted - Regular bundle was generated and notification will be sent to OPA clients",
                        "schema": {
                            "$ref": "#/definitions/handler.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid service parameter",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error during regular bundle generation",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.HttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "err": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "handler.clientGroupResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "handler.httpResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "bundle server",
	Description:      "bundle server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
